import Head from 'next/head'
import Header from './../components/Header'

export default function Home() {
  return (
    <div className="select-none">
      <Head>
        <title>Facebook 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/facebook.png" />
      </Head>
      
      <Header />

      <main></main>
    </div>
  )
}
