import { getSession } from "next-auth/react"
import Head from 'next/head'
import Header from './../components/Header'
import Sidebar from './../components/Sidebar'
import Feed from './../components/Feed'
import Widgets from './../components/Widgets'
import Login from './../components/Login'

export default function Home({session}) {
  if (!session) {
    return <Login />
  }
  else {
    return (
      <div className="select-none">
        <Head>
          <title>Facebook 2.0</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/facebook.png" />
        </Head>
        
        <Header />

        <main className="flex">
          <Sidebar />
          <Feed />
          <Widgets />
        </main>
      </div>
    )
  }
}

export async function getServerSideProps(context){
  const session = await getSession(context);
  return {
    props: {
      session
    }
  }
}
